spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  mail:
    host: localhost
    port: 2525
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.chatpoc: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.testcontainers: WARN